### ISSUE TITLE
npm install react-router@4.0.0-alpha.5

### ISSUE THREAD

**Issue by apn-jun** [mhaagens/react-mobx-react-router4-boilerplate#11]
bash-3.2$ npm install
npm WARN react-router-loader@0.5.4 requires a peer of react-router@>1.0.0 || >2.0.0-rc1 but none
 was installed.
bash-3.2$ npm install react-router-loader --save-dev
MartinsReactBoilerplate@1.0.0 /Users/junwang/Documents/react-mobx-react-router4-boilerplate
├── UNMET PEER DEPENDENCY react-router@4.0.0-alpha.5
└── react-router-loader@0.5.4

**Comment by stocksp** [comment]
Its now
UNMET PEER DEPENDENCY react-router@4.0.0-alpha.6

**Comment by mhaagens** [comment]
React Router-loader will be switched out shortly for a MatchAsync component with System.import instead of require.ensure, planning on pushing it this week.

**Comment by petr001** [comment]
well, i cloned a repo now, but it failed with following error:

```
~/dev/react-mobx-react-router4-boilerplate $ npm start

> MartinsReactBoilerplate@1.0.0 start ~/dev/react-mobx-react-router4-boilerplate
> node devserver.js

keywords if/then/else require v5 option
Listening at http://localhost:3000/
~/dev/react-mobx-react-router4-boilerplate/node_modules/loader-runner/lib/loadLoader.js:35
			throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");
```

It looks like it's caused because of unmet dependency. Is there any plan to update the project to make it work again?

**Comment by mininternet** [comment]
Looks like it's still broken due to this unmet React Router 4 Alpha dependency.

Any update on this? Seems like a really great boilerplate, but routing is currently painful.

**Comment by mhaagens** [comment]
I've removed react-router-loader in favour of Lazy-Route which uses System.import.
Can you try to pull the new version and see if it works for you now?

**Comment by mininternet** [comment]
Looks good! Working now.
