### ISSUE TITLE
loeader-runner issue

### ISSUE THREAD

**Issue by akusany2** [mhaagens/react-mobx-react-router4-boilerplate#13]
Hi, just installed and started the app. Getting errors:

/react-mobx-react-router4-boilerplate/node_modules/loader-runner/lib/loadLoader.js:35
			throw new Error("Module '" + loader.path + "' is not a loader (must have normal or pitch function)");

npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.9
3 info using node@v7.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle MartinsReactBoilerplate@1.0.0~prestart: MartinsReactBoilerplate@1.0.0
6 silly lifecycle MartinsReactBoilerplate@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle MartinsReactBoilerplate@1.0.0~start: MartinsReactBoilerplate@1.0.0
8 verbose lifecycle MartinsReactBoilerplate@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle MartinsReactBoilerplate@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/ankitkr/Desktop/NodeJS/react-mobx-react-router4-boilerplate/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle MartinsReactBoilerplate@1.0.0~start: CWD: /Users/ankitkr/Desktop/NodeJS/react-mobx-react-router4-boilerplate
11 silly lifecycle MartinsReactBoilerplate@1.0.0~start: Args: [ '-c', 'node devserver.js' ]
12 silly lifecycle MartinsReactBoilerplate@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle MartinsReactBoilerplate@1.0.0~start: Failed to exec start script
14 verbose stack Error: MartinsReactBoilerplate@1.0.0 start: `node devserver.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid MartinsReactBoilerplate@1.0.0
16 verbose cwd /Users/ankitkr/Desktop/NodeJS/react-mobx-react-router4-boilerplate
17 error Darwin 16.1.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.2.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error MartinsReactBoilerplate@1.0.0 start: `node devserver.js`
22 error Exit status 1
23 error Failed at the MartinsReactBoilerplate@1.0.0 start script 'node devserver.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the MartinsReactBoilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node devserver.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs MartinsReactBoilerplate
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls MartinsReactBoilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by thomasjonas** [comment]
I had the same problem... I fixed it by using Yarn instead of NPM.

**Comment by akusany2** [comment]
Yes, installing modules with Yarn did fixed it! thanks @thomasjonas
