### ISSUE TITLE
Any plans on adding a typescript boilerplate?

### ISSUE THREAD

**Issue by vrokolos** [mhaagens/react-mobx-react-router4-boilerplate#2]

**Comment by mhaagens** [comment]
Unfortunately not, haven't gotten started using TypeScript yet, but I definitely plan on looking into it soon.

**Comment by deivers** [comment]
I vote for including TypeScript!

**Comment by frederickfogerty** [comment]
We're planning to use this boilerplate for a project, starting in the middle - end of November. We've got lots of experience with typescript + webpack + mobx, so if it's not done by then, we'll see what we can do to help out at that time.

**Comment by psulek** [comment]
@mhaagens Hi, i just finished converting this repo into typescript boilerplate. Just curious if you want this to be under your repo as branch (eg "typescript") or should i create my own new repo (eg. "react-mobx-react-router4-typescript-boilerplate") and write back ref to your original JS repo?
What do you thing?

**Comment by orouz** [comment]
@psulek can you share your repo ?

**Comment by empz** [comment]
@psulek I'd like that repo too if possible =)

**Comment by psulek** [comment]
For anyone interested in typescript version, check out my new repo - [react-mobx-react-router4-typescript-boilerplate](https://github.com/psulek/react-mobx-react-router4-typescript-boilerplate).
