### ISSUE TITLE
Just a heads up System.import is now deprecated

### ISSUE THREAD

**Issue by cjke** [mhaagens/react-mobx-react-router4-boilerplate#22]
Stumbled upon your awesome boilerplate via reddit (as I'm trying to come with an ideal solution for RR4 + WP2). 

Anywho, It seems WP2 has deprecated system.import. 

Notes: 
https://webpack.js.org/guides/code-splitting-import/#system-import-is-deprecated

**Comment by mhaagens** [comment]
Thanks, syntax has been updated!
