### ISSUE TITLE
Question: Has someone implemented Facebook login on top of this boilerplate?

### ISSUE THREAD

**Issue by gkbn** [mhaagens/react-mobx-react-router4-boilerplate#25]
Hi there folks! Has someone implemented Facebook (and/or Google, Twitter) login on top of this boilerplate and would you like to share the code changes as a different branch or something? I need to implement all the three logins for the Web App that I am creating. Have seen the login code outside of MobX (example: Facebook's own documentation of the Javascript API and PassportJS) but not sure how it can be integrated with MobX based apps. Any help with this will be much appreciated. 

This maybe a silly question for experienced frontend developers out there. I am new to all the frontend technologies including Javascript, so please forgive my ignorance if this sounds too basic.

**Comment by orouz** [comment]
@gkbn  you should look into firebase. they provide the easiest social authentication i've encountered.

**Comment by gkbn** [comment]
thanks a lot @orouz! i decided to go with aws cognito as i'm planning to host on aws.
