### ISSUE TITLE
Licensing on this project and lazy route

### ISSUE THREAD

**Issue by gkbn** [mhaagens/react-mobx-react-router4-boilerplate#26]
@mhaagens First of all, thanks a lot for these projects. 

Can you please let me know what licensing applies to this boilerplate and the LazyRoute project used by this? Would you be able to add the licensing terms to the projects?

Thanks in advance!

**Comment by johelaq** [comment]
This project is ISC and Lazy Route is MIT

**Comment by mhaagens** [comment]
Sorry for the late reply, consider this MIT licensed as well, I'll update the licensing terms tomorrow. Thanks for getting involved with the project Johel!
