### ISSUE TITLE
TypeError: this.context.router.createHref is not a function

### ISSUE THREAD

**Issue by pvijeh** [mhaagens/react-mobx-react-router4-boilerplate#27]
The code for this app is currently broken out of the box.

I get this error after running npm install and then npm start: 

![image](https://cloud.githubusercontent.com/assets/9544508/24205661/5fd7fe26-0ef2-11e7-9ee5-2f47c8f7d356.png)

TypeError: this.context.router.createHref is not a function
Link.render
webpack:///./~/react-router-dom/Link.js?:72:36
eval
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:796:21
measureLifeCyclePerf
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:75:12
ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:795:25
ReactCompositeComponentWrapper._renderValidatedComponent
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:822:32
ReactCompositeComponentWrapper.performInitialMount
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:362:30
ReactCompositeComponentWrapper.mountComponent
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:258:21
Object.mountComponent
webpack:///./~/react-dom/lib/ReactReconciler.js?:46:35
ReactCompositeComponentWrapper.performInitialMount
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:371:34
ReactCompositeComponentWrapper.mountComponent
webpack:///./~/react-dom/lib/ReactCompositeComponent.js?:258:21

**Comment by orouz** [comment]
@pvijeh upgrade react router dom to version 4.0.0
