### ISSUE TITLE
There are two spell error in your porject.

### ISSUE THREAD

**Issue by zhouchunyu** [mhaagens/react-mobx-react-router4-boilerplate#28]
It's a great start bolierplate. Personally I thought it's the best. 
However the spell error in it is a little confused for a beginner like me.
  app.js:45 Subitem  should be SubItem
  todo.js:4 Activelink should be ActiveLink
Anyway, thanks for sharing such a good boilerplate.

**Comment by mhaagens** [comment]
Fixed.
