### ISSUE TITLE
fresh download of boilerplate fails to compile

### ISSUE THREAD

**Issue by djstauffer** [mhaagens/react-mobx-react-router4-boilerplate#33]
I just checkout out a fresh copy of this, ran npm install and npm start.  Here is the result of the npm start:

> ERROR in ./src/components/App.js
Module not found: Error: Can't resolve './SubPage' in '{somewhere-in-my-home-dir}/react-mobx-react-router4-boilerplate/src/components'
 @ ./src/components/App.js 74:79-98
 @ ./src/index.js
 @ multi react-hot-loader/patch babel-polyfill whatwg-fetch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./src/index

Obviously the {somewhere-in-my-home-dir} part isn't literal, it was the absolute path in my home dir to the checked-out project.

I'm running node version v6.10.1 and npm version 3.10.10 on debian jessie.

**Comment by Corey-Maler** [comment]
In linux systems `import` is case-sensitive unlike Mac OS. The problem is file named as `Subpage.js` instead `SubPage.js` (same issue with file `ActiveLink.js`).

**Comment by djstauffer** [comment]
Ah, good catch.  I totally didn't see that the file was named with a lower case 'p', or I would have probably figured that out.  I also didn't know that Macs did imports case-insensitive (but I haven't done any work with node on a Mac).
