### ISSUE TITLE
Doesn't work with HashRouter

### ISSUE THREAD

**Issue by Xilonz** [mhaagens/react-mobx-react-router4-boilerplate#34]
I used lots of your boilerplate, but the order in which the components are stacked don't work for me. 
The <Provider> components make the <Router>'s component context fail. I ended up switching the 2 components. So, first the <Provider> and then the <Router>.

**Comment by mhaagens** [comment]
Works on my end, are you getting any errors?

**Comment by mhaagens** [comment]
Closed due to inactivity.
