### ISSUE TITLE
Can't resolve './ui/Activelink'

### ISSUE THREAD

**Issue by DmitryNoven** [mhaagens/react-mobx-react-router4-boilerplate#36]
Uncaught Error: Cannot find module "./ui/Activelink"
When i`m running npm run preview

**Comment by jgunnison** [comment]
I'm guessing it's due to the "link" part not being uppercase in the import. Just change that to  "./ui/ActiveLink" and it should work just fine. Personally I installed `case-sensitive-paths-webpack-plugin` for my project that started with this boilerplate to catch these issues.

**Comment by DmitryNoven** [comment]
Thank you). That`s solves this this problem)
