### ISSUE TITLE
Access to posts url also when signed out

### ISSUE THREAD

**Issue by therealmarv** [mhaagens/react-mobx-react-router4-boilerplate#4]
Thanks for this boilerplate! Only recognized this small bug:
When signed out and going to https://boilerplate.mhaagens.me/posts I'm automatically logged in again. Would be nice to see a very simple "login page" with maybe two buttons like "login success" and "login failure" and beeing redirected to posts after success.

But maybe I'm thinking already too far from a boilerplate code ;) Thanks for sharing this boilerplate!

**Comment by mhaagens** [comment]
Hi, glad you find the boilerplate useful!
The app is automatically authenticated when you load it, so if you manually go to /posts you will be indeed be authenticated. This is to "fake" the flow of loading localStorage tokens and sign you in automatically on load (in the simplest way possible). So the idea is that you change the authenticate function to actually go to an API endpoint to verify tokens and then take an action based on the response (authenticated or not authenticated). I might implement a login page soon though, I can keep the posts menu option there even when not signed i,n and then redirect to the login on click, that way you can see the login flow as well without reloading the page and being automatically authenticated. Thanks for the feedback! :)
