### ISSUE TITLE
display images

### ISSUE THREAD

**Issue by strowbeary** [mhaagens/react-mobx-react-router4-boilerplate#46]
Hello,
I would like to diplay images with a component 
`<Image name="logo.svg"/> `
and i don't know wich path i can use.
How to load images with their paths/names ?

Thank you

**Comment by mhaagens** [comment]
If you want to load it inside your component you need to require the image file like this (relative to the directory of your component);

```const myImage = require("../images/myimage.png");```

Then you can use it like this;

```<img src={myImage} />```
