### ISSUE TITLE
RHL 3 and Webpack 2

### ISSUE THREAD

**Issue by echenley** [mhaagens/react-mobx-react-router4-boilerplate#5]
According to [the RHL 3 boilerplate example](https://github.com/gaearon/react-hot-boilerplate/pull/61/files#diff-1fdf421c05c1140f6d71444ea2b27638R18), [this line](https://github.com/mhaagens/react-mobx-react-router4-boilerplate/blob/master/src/index.js#L20) shouldn't be necessary with webpack 2.0. Did you do it this way intentionally?

Just wondering because I attempted Webpack 2.0 and RHL 3 at one point and had a lot of trouble getting it working (the hot accept callback never fired).

Thanks for the demo!

**Comment by mhaagens** [comment]
I've seen that gist before, it doesn't seem to work, but I'm trying to figure it out.
