### ISSUE TITLE
Router not working? 

### ISSUE THREAD

**Issue by kristiansorens** [mhaagens/react-mobx-react-router4-boilerplate#55]
Seems like the router is not working properly when I run it local? Clicking the links in the top-bar will change the url, but it will not change the view. 

This happens after fresh install, nothing changed other than a minor dependency issue (missing file-loader).

Am I missing something?

**Comment by awwilhelm** [comment]
I am experiencing this too.  I think it has something to do with Provider from mobx-react, but I do not know for sure yet.

**Comment by kristiansorens** [comment]
@awwilhelm let me know if you find a solution for this!

**Comment by mhaagens** [comment]
Should be fixed by d0fbe0b0feea17c9ae5535e28c6c2e1b03e3be67.
Please pull the latest version and let me know if it works again.

**Comment by kristiansorens** [comment]
@mhaagens Sorry it took me a while to get back to you. It is working perfectly now! thanks!
