### ISSUE TITLE
Question - not Issue - with rendering nested objects in SubItem

### ISSUE THREAD

**Issue by seanrasmussen** [mhaagens/react-mobx-react-router4-boilerplate#6]
I apologize for the newbie question, but when I use a different endpoint in the aysnc call in the store it all works great, except for nested objects. 

In SubItem
This works: {this.store.item.slug}
but this doesn't:
{this.store.item.title.rendered}    <-- TypeError: Cannot read property 'rendered' of undefined(…)

Top level objects are fine, but not nested ones... How would I access the nested object without the undefined. I have googled this six different ways. Thanks!

**Comment by mhaagens** [comment]
It's kind of hard to debug without seeing the code, could you share a gist with me with the relevant code (make it a secret gist if you want) and I'll take a look?

**Comment by seanrasmussen** [comment]
Here is a gist that shows the code... Thanks!

https://gist.github.com/seanrasmussen/bca07baea498a3b5a52836e1ba4bf957

**Comment by mhaagens** [comment]
On my phone right now so I'll have to look at it tomorrow, but can you try to change 
`this.setSingle(data)`
to 
`this.setSingle(data[0])`
in the store and see if that helps?

**Comment by seanrasmussen** [comment]
Thanks -- I tried that but didn't seem to work.... 

I have run into this single nested object issue before, and ended up grabbing values from the store and setting state and passing state onwards to a component that displays it... Kinda klugey and hoping to use your nice solution instead.... 

Some discussions on this suggest that the object might not be fully loaded at time of render (but you have it conditionally displayed, though) so that doesn't seem to make sense....

**Comment by mhaagens** [comment]
Weird. Yeah, I'm out at the moment but I'll take a closer look once I get home. We'll figure it out :)

**Comment by seanrasmussen** [comment]
Here's a gist of a workaround that works:
https://gist.github.com/seanrasmussen/785e16de516eeef7d42739a952814cd2

I still want to know why I can't just use a single nested object in react render, though...
